resolver: lts-23.7

# This repo contains multiple versions of kubernetes-api, in the
# kubernetes-api-* directories.
# You should use exactly one to build against.
packages:
- kubernetes-api-1.30
- kubernetes-api-client

extra-deps:
- git: https://github.com/codedownio/haskell-oidc-client
  # codedown-jun-2024-ghc98
  commit: b70757b85751525cba41316ea9af132d9a43cfaf

nix:
  pure: false
  packages:
  - zlib
